---
title: "Exam 2: Food Consumption 2"
format: html
---

First we need to load all packages necessary for the spatial and processing parts of this visualization process.
```{r libraries}
library(tidytuesdayR)
library(tidyverse)
library(forcats)
library(rnaturalearth)
library(sf)
```


```{r data-import}
tuesdata <- tt_load('2020-02-18')
fc <- as.data.frame(tuesdata$food_consumption)
str(fc)
head(fc, 22)
```

```{r inspect data}
fc |>
distinct(food_category) # This part of analysis shows that we need to shorten some of these names before we can visualize them.


```

```{r variable name change}
fc$food_category <- fct_recode(fc$food_category,
             Lamb = "Lamb & Goat",
             Dairy = "Milk - inc. cheese",
             Wheat = "Wheat and Wheat Products",
             Nuts = "Nuts inc. Peanut Butter")

fc |>
distinct(food_category) #To check that the categories have been successfully changed
```
Research Question 1: Which countries consume the most food total?
```{r}
fc_mostfood <- fc |>
  group_by(country) |>
  mutate(total_consumption = sum(consumption)) |>
  summarize(country, mean = mean(total_consumption)) |>
  unique() |>
  arrange(desc(mean)) |>
  head(5)

fc_mostfood |>
  ggplot(aes(x = country, y = mean)) +
  geom_bar(stat = "identity") +
  labs(y = "Total Consumption")

```
Research Question 2: Which countries consume the most of each unique food category?
```{r, fig.width = 8, fig.height = 10}
fc_mosteachcat <- fc |>
  group_by(food_category) |>
  slice_max(consumption, n = 5)

fc_mosteachcat |>
  ggplot(aes(x = reorder(as.factor(country), consumption), y = consumption)) +
  geom_point(stat = "identity") +
  facet_wrap(~food_category, scales = "free") +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Country")


```

Research Question 3: What does the consumption of each food look like?
```{r}
ne_countries(returnclass = "sf") |>
  left_join(world_boundaries)

```







